from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acec80b2659'
down_revision = '3acrc30b2659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('email_sender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail')
    # ### end Alembic commands ###
