"""таблица order

Revision ID: df4e7bed4063
Revises: 520f2ff242af
Create Date: 2020-04-28 20:53:16.142144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4e7bed4063'
down_revision = '520f2ff242af'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('town', sa.VARCHAR(), nullable=True),
    sa.Column('street', sa.VARCHAR(), nullable=True),
    sa.Column('house', sa.VARCHAR(), nullable=True),
    sa.Column('flat', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.Column('porch', sa.VARCHAR(), nullable=True),
    sa.Column('floor', sa.VARCHAR(), nullable=True),
    sa.Column('your_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('is_not_adopted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_adopted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_getting_ready', sa.BOOLEAN(), nullable=True),
    sa.Column('is_delivering', sa.BOOLEAN(), nullable=True),
    sa.Column('is_waiting', sa.BOOLEAN(), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('is_adopted IN (0, 1)'),
    sa.CheckConstraint('is_delivering IN (0, 1)'),
    sa.CheckConstraint('is_done IN (0, 1)'),
    sa.CheckConstraint('is_getting_ready IN (0, 1)'),
    sa.CheckConstraint('is_not_adopted IN (0, 1)'),
    sa.CheckConstraint('is_waiting IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
